# Generated by Django 5.1.1 on 2024-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='currentJob',
            field=models.CharField(default='Unemployed', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='currentLocation',
            field=models.CharField(default='Nowhere', max_length=120),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='shortDesc',
            field=models.CharField(default='Relatively hard-working and normal human being', max_length=100),
        ),
    ]
